baseurl = "https://yefri97.github.io/aima-exercise-test"
languageCode = "en-us"
title = "Exercises of the AIMA book"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    exercises = "/:filename"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Exercises"
    url = "/chapters/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[taxonomies]
    chapter = "chapters"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Yefri Gaitan](https://github.com/Yefri97) 2018 | [Github](https://github.com/Yefri97/aima-exercise-test) | [Twitter](#)"
